name: Build Fork
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      is_tag: ${{ startsWith(github.ref, 'refs/tags/v') }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      # Windows fix. See https://github.com/actions/checkout/issues/226
      - run: git config --global core.autocrlf false

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

       # Because of timeout issue https://github.com/yarnpkg/yarn/issues/4890
      - run: yarn install --immutable --network-timeout 1000000

      - name: (MacOS) Download ffmpeg
        if: startsWith(matrix.os, 'macos')
        run: |
          yarn download-ffmpeg-darwin-x64
          yarn download-ffmpeg-darwin-arm64

      - name: (Windows) Download ffmpeg
        if: startsWith(matrix.os, 'windows')
        run: yarn download-ffmpeg-win32-x64

      - name: (Linux) Download ffmpeg
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn download-ffmpeg-linux-x64

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ env.is_tag == 'true' }}

          max_attempts: 1
